export const SERVICE_REPOSITORY_PROVIDE = Symbol('SERVICE_REPOSITORY_PROVIDE');
export const SERVICE_SERVICE_PROVIDE = Symbol('SERVICE_SERVICE_PROVIDE');

export const SERVICE_CREATE_USE_CASE_PROVIDE = Symbol('SERVICE_CREATE_USE_CASE_PROVIDE');
export const SERVICE_UPDATE_USE_CASE_PROVIDE = Symbol('SERVICE_UPDATE_USE_CASE_PROVIDE');
export const SERVICE_GET_BY_ID_USE_CASE_PROVIDE = Symbol('SERVICE_GET_BY_ID_USE_CASE_PROVIDE');
export const SERVICE_LIST_USE_CASE_PROVIDE = Symbol('SERVICE_LIST_USE_CASE_PROVIDE');
