export const SERVICE_REQUEST_REPOSITORY_PROVIDE = Symbol('SERVICE_REQUEST_REPOSITORY_PROVIDE');
export const SERVICE_REQUEST_SERVICE_PROVIDE = Symbol('SERVICE_REQUEST_SERVICE_PROVIDE');

export const SERVICE_REQUEST_CREATE_USE_CASE_PROVIDE = Symbol('SERVICE_REQUEST_CREATE_USE_CASE_PROVIDE');
export const SERVICE_REQUEST_GET_BY_ID_USE_CASE_PROVIDE = Symbol('SERVICE_REQUEST_GET_BY_ID_USE_CASE_PROVIDE');
export const SERVICE_REQUEST_LIST_BY_USER_USE_CASE_PROVIDE = Symbol('SERVICE_REQUEST_LIST_BY_USER_USE_CASE_PROVIDE');
export const SERVICE_REQUEST_LIST_BY_PROVIDER_USE_CASE_PROVIDE = Symbol('SERVICE_REQUEST_LIST_BY_PROVIDER_USE_CASE_PROVIDE');
export const SERVICE_REQUEST_ACCEPT_USE_CASE_PROVIDE = Symbol('SERVICE_REQUEST_ACCEPT_USE_CASE_PROVIDE');
export const SERVICE_REQUEST_REJECT_USE_CASE_PROVIDE = Symbol('SERVICE_REQUEST_REJECT_USE_CASE_PROVIDE');
export const SERVICE_REQUEST_COMPLETE_USE_CASE_PROVIDE = Symbol('SERVICE_REQUEST_COMPLETE_USE_CASE_PROVIDE');
export const SERVICE_REQUEST_CANCEL_USE_CASE_PROVIDE = Symbol('SERVICE_REQUEST_CANCEL_USE_CASE_PROVIDE');
