export const NOTIFICATION_REPOSITORY_PROVIDE = Symbol('NOTIFICATION_REPOSITORY_PROVIDE');
export const NOTIFICATION_SERVICE_PROVIDE = Symbol('NOTIFICATION_SERVICE_PROVIDE');
export const NOTIFICATION_LIST_USE_CASE_PROVIDE = Symbol('NOTIFICATION_LIST_USE_CASE_PROVIDE');
export const NOTIFICATION_MARK_READ_USE_CASE_PROVIDE = Symbol('NOTIFICATION_MARK_READ_USE_CASE_PROVIDE');
