export const REVIEW_REPOSITORY_PROVIDE = Symbol('REVIEW_REPOSITORY_PROVIDE');
export const REVIEW_SERVICE_PROVIDE = Symbol('REVIEW_SERVICE_PROVIDE');
export const REVIEW_CREATE_USE_CASE_PROVIDE = Symbol('REVIEW_CREATE_USE_CASE_PROVIDE');
export const REVIEW_LIST_BY_PROVIDER_USE_CASE_PROVIDE = Symbol('REVIEW_LIST_BY_PROVIDER_USE_CASE_PROVIDE');
