export const PROVIDER_REPOSITORY_PROVIDE = Symbol('PROVIDER_REPOSITORY_PROVIDE');
export const PROVIDER_SERVICE_PROVIDE = Symbol('PROVIDER_SERVICE_PROVIDE');

export const PROVIDER_CREATE_USE_CASE_PROVIDE = Symbol('PROVIDER_CREATE_USE_CASE_PROVIDE');
export const PROVIDER_GET_BY_ID_USE_CASE_PROVIDE = Symbol('PROVIDER_GET_BY_ID_USE_CASE_PROVIDE');
export const PROVIDER_LIST_USE_CASE_PROVIDE = Symbol('PROVIDER_LIST_USE_CASE_PROVIDE');
export const PROVIDER_UPDATE_USE_CASE_PROVIDE = Symbol('PROVIDER_UPDATE_USE_CASE_PROVIDE');
export const PROVIDER_ADD_SERVICE_USE_CASE_PROVIDE = Symbol('PROVIDER_ADD_SERVICE_USE_CASE_PROVIDE');
export const PROVIDER_REMOVE_SERVICE_USE_CASE_PROVIDE = Symbol('PROVIDER_REMOVE_SERVICE_USE_CASE_PROVIDE');
export const PROVIDER_ADD_WORK_LOCATION_USE_CASE_PROVIDE = Symbol('PROVIDER_ADD_WORK_LOCATION_USE_CASE_PROVIDE');
export const PROVIDER_REMOVE_WORK_LOCATION_USE_CASE_PROVIDE = Symbol('PROVIDER_REMOVE_WORK_LOCATION_USE_CASE_PROVIDE');
export const PROVIDER_SUBMIT_VERIFICATION_USE_CASE_PROVIDE = Symbol('PROVIDER_SUBMIT_VERIFICATION_USE_CASE_PROVIDE');
export const PROVIDER_APPROVE_USE_CASE_PROVIDE = Symbol('PROVIDER_APPROVE_USE_CASE_PROVIDE');
export const PROVIDER_REJECT_USE_CASE_PROVIDE = Symbol('PROVIDER_REJECT_USE_CASE_PROVIDE');
export const PROVIDER_LIST_PENDING_USE_CASE_PROVIDE = Symbol('PROVIDER_LIST_PENDING_USE_CASE_PROVIDE');
export const PROVIDER_GET_VERIFICATION_USE_CASE_PROVIDE = Symbol('PROVIDER_GET_VERIFICATION_USE_CASE_PROVIDE');
