export const CATEGORY_REPOSITORY_PROVIDE = Symbol('CATEGORY_REPOSITORY_PROVIDE');
export const CATEGORY_SERVICE_PROVIDE = Symbol('CATEGORY_SERVICE_PROVIDE');
export const CATEGORY_CREATE_USE_CASE_PROVIDE = Symbol('CATEGORY_CREATE_USE_CASE_PROVIDE');
export const CATEGORY_UPDATE_USE_CASE_PROVIDE = Symbol('CATEGORY_UPDATE_USE_CASE_PROVIDE');
export const CATEGORY_DELETE_USE_CASE_PROVIDE = Symbol('CATEGORY_DELETE_USE_CASE_PROVIDE');
export const CATEGORY_LIST_USE_CASE_PROVIDE = Symbol('CATEGORY_LIST_USE_CASE_PROVIDE');
export const CATEGORY_GET_BY_ID_USE_CASE_PROVIDE = Symbol('CATEGORY_GET_BY_ID_USE_CASE_PROVIDE');
