export const DOCUMENT_REPOSITORY_PROVIDE = Symbol('DOCUMENT_REPOSITORY_PROVIDE');
export const DOCUMENT_SERVICE_PROVIDE = Symbol('DOCUMENT_SERVICE_PROVIDE');
export const DOCUMENT_UPLOAD_USE_CASE_PROVIDE = Symbol('DOCUMENT_UPLOAD_USE_CASE_PROVIDE');
export const DOCUMENT_APPROVE_USE_CASE_PROVIDE = Symbol('DOCUMENT_APPROVE_USE_CASE_PROVIDE');
export const DOCUMENT_REJECT_USE_CASE_PROVIDE = Symbol('DOCUMENT_REJECT_USE_CASE_PROVIDE');
export const DOCUMENT_GET_URL_USE_CASE_PROVIDE = Symbol('DOCUMENT_GET_URL_USE_CASE_PROVIDE');
